### ISSUE TITLE
Config --> Preferences --> Radio -- Check on Ratflector status

### ISSUE THREAD

**Issue by maurizioandreotti** [ham-radio-software/D-Rats#42] opened 2020-04-27 07:46 UTC
In the Config --> Preferences --> Radio view, would it be possible to add an indicator of which connections are ACTIVE?   This would be an easy way to determine which remote Ratflectors are working or not.

you mean a sort of a ping to check the ratflector before marking it as active?

**Comment by dranch** [comment] 2020-04-27 17:59
If you look at the D-rats "event log" tab, you can see which remote RAT hosts accept or refuse connections but it's tedious to see what stations work.  There also isn't a clear association of what hostname corresponds to which alias name in the the Event log.

drats.ratflector.com - connection timed out
ref.d-rats.com - connection refused
k3pdr rat - connected
wa7fw.dstargateway.org - connected

**Comment by wb8tyw** [comment] 2023-04-05 23:42
This is essentially a duplicate of https://github.com/ham-radio-software/D-Rats/issues/74 which has more discussion on it.

**Closed by wb8tyw** 2023-04-05 23:42 UTC
Labels: duplicate, enhancement
